"""Constants used by kids API routes."""
import os

MIN_SESSION_CARD_COUNT = 1
DEFAULT_HARD_CARD_PERCENTAGE = 0
MIN_HARD_CARD_PERCENTAGE = 0
MAX_HARD_CARD_PERCENTAGE = 100
DEFAULT_INCLUDE_ORPHAN_IN_QUEUE = True
TYPE_I_NON_CHINESE_DECK_MIX_FIELD = 'sharedMathDeckMix'
SESSION_CARD_COUNT_BY_CATEGORY_FIELD = 'sessionCardCountByCategory'
HARD_CARD_PERCENT_BY_CATEGORY_FIELD = 'hardCardPercentageByCategory'
INCLUDE_ORPHAN_BY_CATEGORY_FIELD = 'includeOrphanByCategory'
PRACTICE_PRIORITY_REASON_MISSED = 'missed'
PRACTICE_PRIORITY_REASON_SLOW = 'slow'
PRACTICE_PRIORITY_REASON_LEARNING = 'learning'
PRACTICE_PRIORITY_REASON_DUE = 'due'
PRACTICE_PRIORITY_LAST_FAILED_BOOST = 0.80
PRACTICE_PRIORITY_MIN_CORRECT_RECORDS_FOR_SPEED_BASELINE = 100
PRACTICE_PRIORITY_MISSED_WEIGHT = 45.0
PRACTICE_PRIORITY_SLOW_WEIGHT = 25.0
PRACTICE_PRIORITY_LEARNING_WEIGHT = 20.0
PRACTICE_PRIORITY_DUE_WEIGHT = 10.0
PRACTICE_PRIORITY_LEARNING_TARGET_ATTEMPTS = 5.0
PRACTICE_PRIORITY_VERY_DUE_DAYS = 30.0
BACKEND_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
DATA_DIR = os.path.join(BACKEND_ROOT, 'data')
FAMILIES_ROOT = os.path.join(DATA_DIR, 'families')
DECK_CATEGORY_BEHAVIOR_TYPE_I = 'type_i'
DECK_CATEGORY_BEHAVIOR_TYPE_II = 'type_ii'
DECK_CATEGORY_BEHAVIOR_TYPE_III = 'type_iii'
DECK_CATEGORY_BEHAVIOR_TYPE_IV = 'type_iv'
DECK_CATEGORY_BEHAVIOR_TYPES = {
    DECK_CATEGORY_BEHAVIOR_TYPE_I,
    DECK_CATEGORY_BEHAVIOR_TYPE_II,
    DECK_CATEGORY_BEHAVIOR_TYPE_III,
    DECK_CATEGORY_BEHAVIOR_TYPE_IV,
}
MAX_SHARED_DECK_TAGS = 20
MAX_SHARED_DECK_CARDS = 10000
MAX_SHARED_TAG_LENGTH = 64
MAX_SHARED_TAG_COMMENT_LENGTH = 120
MAX_TYPE_IV_DISPLAY_LABEL_LENGTH = 120
MAX_TYPE_IV_GENERATOR_CODE_LENGTH = 20000
MAX_TYPE_IV_PRINT_CELL_DIMENSION = 4000
MAX_TYPE_IV_PRINT_CELL_OFFSET = 4000
MAX_TYPE_IV_PRINT_CANVAS_VERSION = 1000
MAX_TYPE_IV_PRINT_SAMPLE_PROMPT_LENGTH = 500
MAX_TYPE_IV_PRINT_SAMPLE_ANSWER_LENGTH = 200
TYPE_IV_PRINT_SHEET_LAYOUT_VERSION = 1
TYPE_IV_PRINT_SHEET_MIN_SCALE = 0.5
TYPE_IV_PRINT_SHEET_MAX_SCALE = 1.7
TYPE_IV_PRINT_SHEET_MIN_INLINE_FONT_SCALE = 0.8
TYPE_IV_PRINT_SHEET_MAX_INLINE_FONT_SCALE = 3.0
TYPE_IV_PRINT_SHEET_MAX_ROW_PROBLEMS = 200
TYPE_IV_PRINT_SHEET_MAX_REPEAT_COUNT = 1000
TYPE_IV_PRINT_SHEET_PAPER_SIZE_A4 = 'a4'
TYPE_IV_PRINT_SHEET_PAPER_SIZE_LETTER = 'letter'
DEFAULT_TYPE_IV_PRINT_SHEET_PAPER_SIZE = TYPE_IV_PRINT_SHEET_PAPER_SIZE_LETTER
TYPE_IV_PRINT_SHEET_A4_WIDTH = 794
TYPE_IV_PRINT_SHEET_A4_HEIGHT = 1123
TYPE_IV_PRINT_SHEET_LETTER_WIDTH = 816
TYPE_IV_PRINT_SHEET_LETTER_HEIGHT = 1056
TYPE_IV_PRINT_SHEET_MARGIN = 19
TYPE_IV_PRINT_SHEET_EXTRA_SAFE_MARGIN_X = 34
TYPE_IV_PRINT_SHEET_EXTRA_SAFE_MARGIN_TOP = 42
TYPE_IV_PRINT_SHEET_EXTRA_SAFE_MARGIN_BOTTOM = 42
TYPE_IV_PRINT_SHEET_HEADER_HEIGHT = 24
TYPE_IV_PRINT_SHEET_FIT_SAFETY_PX = 12
TYPE_IV_PRINT_SHEET_PAPER_SPECS = {
    TYPE_IV_PRINT_SHEET_PAPER_SIZE_A4: {
        'page_width': TYPE_IV_PRINT_SHEET_A4_WIDTH,
        'page_height': TYPE_IV_PRINT_SHEET_A4_HEIGHT,
    },
    TYPE_IV_PRINT_SHEET_PAPER_SIZE_LETTER: {
        'page_width': TYPE_IV_PRINT_SHEET_LETTER_WIDTH,
        'page_height': TYPE_IV_PRINT_SHEET_LETTER_HEIGHT,
    },
}
for _type_iv_paper_spec in TYPE_IV_PRINT_SHEET_PAPER_SPECS.values():
    _type_iv_paper_spec['grid_width'] = (
        _type_iv_paper_spec['page_width'] - (2 * TYPE_IV_PRINT_SHEET_MARGIN)
    )
    _type_iv_paper_spec['grid_height'] = (
        _type_iv_paper_spec['page_height'] - (2 * TYPE_IV_PRINT_SHEET_MARGIN)
    )
    _type_iv_paper_spec['box_width'] = (
        _type_iv_paper_spec['grid_width'] - (2 * TYPE_IV_PRINT_SHEET_EXTRA_SAFE_MARGIN_X)
    )
    _type_iv_paper_spec['box_height'] = (
        _type_iv_paper_spec['grid_height']
        - TYPE_IV_PRINT_SHEET_EXTRA_SAFE_MARGIN_TOP
        - TYPE_IV_PRINT_SHEET_EXTRA_SAFE_MARGIN_BOTTOM
    )
    _type_iv_paper_spec['content_height'] = (
        _type_iv_paper_spec['box_height'] - TYPE_IV_PRINT_SHEET_HEADER_HEIGHT
    )
    _type_iv_paper_spec['safe_grid_height'] = (
        _type_iv_paper_spec['content_height'] - TYPE_IV_PRINT_SHEET_FIT_SAFETY_PX
    )
DEFAULT_TYPE_IV_DAILY_TARGET_COUNT = 10
MAX_TYPE_IV_DAILY_TARGET_COUNT = 1000
TYPE_IV_PREVIEW_SAMPLE_COUNT = 1
TYPE_IV_DEFAULT_PRACTICE_MODE = 'input'
TYPE_IV_PRACTICE_MODE_INPUT = 'input'
TYPE_IV_PRACTICE_MODE_MULTI = 'multi'
TYPE_IV_MAX_LOGGED_RESPONSE_TIME_MS = 2 * 60 * 1000
MAX_SHARED_DECK_OPTIN_BATCH = 200
MATERIALIZED_SHARED_DECK_NAME_PREFIX = 'shared_deck_'
KID_DECK_CATEGORY_OPT_IN_TABLE = 'deck_category_opt_in'
KID_DECK_CATEGORY_OPT_IN_COL_IS_OPTED_IN = 'is_opted_in'
KID_DECK_CATEGORY_OPT_IN_COL_SESSION_CARD_COUNT = 'session_card_count'
KID_DECK_CATEGORY_OPT_IN_COL_HARD_CARD_PERCENTAGE = 'hard_card_percentage'
KID_DECK_CATEGORY_OPT_IN_COL_INCLUDE_ORPHAN = 'include_orphan'
WRITING_AUDIO_EXTENSION = '.mp3'
WRITING_AUDIO_FILE_NAME_MAX_BYTES = 220
WRITING_TTS_LANGUAGE_ZH = 'zh-CN'
WRITING_TTS_LANGUAGE_EN = 'en'
PENDING_SESSION_TTL_SECONDS = 60 * 60 * 6
TYPE_I_MAX_LOGGED_RESPONSE_TIME_MS = 20 * 1000
TYPE_II_MAX_LOGGED_RESPONSE_TIME_MS = 2 * 60 * 1000
SESSION_RESULT_CORRECT = 1
SESSION_RESULT_PARTIAL = 2
SESSION_RESULT_WRONG_UNRESOLVED = -1
# session_results.correct also carries retry-resolution metadata for type-I/type-II
# star chains. Values mean:
#   1   -> right on the initial session pass
#  -1   -> still wrong and still eligible for another retry session
#  -2   -> was wrong first, then fixed on retry round 1
#  -3   -> was wrong first, then fixed on retry round 2
#  -4   -> was wrong first, then fixed on retry round 3
# and so on. In other words, any value <= -2 means "recovered in retry", and
# abs(correct) - 1 tells us which retry round finally fixed the card.
SESSION_RESULT_RETRY_FIXED_FIRST = -2
MAX_LOGGED_RESPONSE_TIME_MS_BY_BEHAVIOR_TYPE = {
    DECK_CATEGORY_BEHAVIOR_TYPE_I: TYPE_I_MAX_LOGGED_RESPONSE_TIME_MS,
    DECK_CATEGORY_BEHAVIOR_TYPE_II: TYPE_II_MAX_LOGGED_RESPONSE_TIME_MS,
    DECK_CATEGORY_BEHAVIOR_TYPE_IV: TYPE_IV_MAX_LOGGED_RESPONSE_TIME_MS,
}
PENDING_RETRY_SOURCE_SESSION_ID_KEY = 'retry_source_session_id'
PENDING_CONTINUE_SOURCE_SESSION_ID_KEY = 'continue_source_session_id'
